export const STATUS_TYPE_UNKNOW = "UNKNOW";

export const STATUS_TYPE_ACCEPTED = "ACCEPTED";

export const STATUS_TYPE_REJECTED = "REJECTED";

export const STATUS_TEXT_UNKNOW = "";

export const STATUS_TEXT_ACCEPTED = "✔ ACCEPTED";

export const STATUS_TEXT_REJECTED = "✖ REJECTED";
